### ISSUE TITLE
sync_diff_inspector 的 json compare 不正确

### ISSUE THREAD

**Issue by Dieken** [pingcap/tidb-tools#606] opened 2022-03-18 07:26 UTC
https://github.com/pingcap/tidb-tools/blob/master/sync_diff_inspector/utils/utils.go#L535

mysql 按照 key length 排序然后再按词典序，tidb 按照词典序排序，看起来这个地方把 json 解析再序列化下就可以比对了。

func CompareData(map1, map2 map[string]*dbutil.ColumnData, orderKeyCols, columns []*model.ColumnInfo) (equal bool, cmp int32, err error) {

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/2365/158955813-fba7efa3-980e-4996-9444-2accd5e1b569.png">

**Comment by 3pointer** [comment] 2022-04-20 10:28
It's hard to compare json field cause we lost the information of column field. so we cannot do de-serialize here.
For now, you can ignore json field in config.

**Comment by Dieken** [comment] 2022-04-20 10:43
> It's hard to compare json field cause we lost the information of column field. so we cannot do de-serialize here.
> For now, you can ignore json field in config.

你是说对于 json column，其 column.FieldType 并不是 JSON 所以没法对它按照 JSON  反序列化？

忽略 JSON 列的话 sync_diff_inspector 的结果就失去意义了。。。

**Comment by dveeden** [comment] 2022-07-22 08:19
I think wa can consider this a duplicate of #350

**Closed as completed** 2022-09-21 06:01 UTC
